/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.AdminUI;

import Business.ConfigureEcoSystem;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.sql.ResultSet;

/**
 *
 * @author ASUS
 */
public class AdminEnterPrise extends javax.swing.JPanel {

    /**
     * Creates new form AdminEnterPrise
     */
    public AdminEnterPrise() throws SQLException {
        initComponents();
        populateCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxEcoSystem = new javax.swing.JComboBox<>();

        cbxEcoSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEcoSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(cbxEcoSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cbxEcoSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEcoSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEcoSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEcoSystemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxEcoSystem;
    // End of variables declaration//GEN-END:variables

    private void populateCombobox() throws SQLException {
        DefaultComboBoxModel EcosystemCbx = (DefaultComboBoxModel) cbxEcoSystem.getModel();
        EcosystemCbx.removeAllElements();
        ResultSet rs = ConfigureEcoSystem.GetAllEcosystemNames();
        while(rs.next()){
            EcosystemCbx.addElement(rs.getString(1));
            
        }
    }
}
