/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CustomerUI;

import Business.Stores.Products;
import Database.mysqlConnection;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maddukurimonikabhaskar
 */
public class NewOrder extends javax.swing.JPanel {

    /**
     * Creates new form NewOrder
     */
    String CustomerName;
    public NewOrder() {
        initComponents();
        
    }
    public NewOrder(String CustomerName){
        initComponents();
        this.CustomerName = CustomerName;
        lblCustomerName.setText(CustomerName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxSelectStore = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerProductView = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxSelectCompany = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnViewProducts = new javax.swing.JButton();

        jLabel1.setText("Select Store:");

        cbxSelectStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSelectStoreActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Category:");

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All_Categories", "Electronics", "Clothes", "HouseHold", "Food Section" }));

        tblCustomerProductView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Product Category", "Product Price", "Store Name"
            }
        ));
        jScrollPane1.setViewportView(tblCustomerProductView);

        btnPlaceOrder.setText("Place Order");

        jLabel3.setText("Select Company:");

        cbxSelectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSelectCompanyActionPerformed(evt);
            }
        });

        jLabel4.setText("Welcome,");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnViewProducts.setText("View Products");
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnPlaceOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxSelectCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxSelectStore, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnViewProducts)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxSelectCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxSelectStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnViewProducts)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlaceOrder)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSelectStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSelectStoreActionPerformed
       
    }//GEN-LAST:event_cbxSelectStoreActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            // TODO add your handling code here:
            PopulateOrganizations();
        } catch (SQLException ex) {
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cbxSelectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSelectCompanyActionPerformed
        try {
            // TODO add your handling code here:
            PopulateStores();
        } catch (SQLException ex) {
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxSelectCompanyActionPerformed

    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        try {
            // TODO add your handling code here:
            PopulateProductList();
        } catch (SQLException ex) {
            Logger.getLogger(NewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnViewProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxSelectCompany;
    private javax.swing.JComboBox<String> cbxSelectStore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JTable tblCustomerProductView;
    // End of variables declaration//GEN-END:variables

    private void PopulateStores() throws SQLException {
        DefaultComboBoxModel StoreCbx = (DefaultComboBoxModel) cbxSelectStore.getModel();
        StoreCbx.removeAllElements();
        String SelectCompany = (String) cbxSelectCompany.getSelectedItem();
        ResultSet rs = Products.GetAllStoreNames(SelectCompany);
        while(rs.next()){
            StoreCbx.addElement(rs.getString(1));
        }      
    }
    
    private void PopulateOrganizations() throws SQLException {
        DefaultComboBoxModel CompanySelect = (DefaultComboBoxModel) cbxSelectCompany.getModel();
        CompanySelect.removeAllElements();
        String Sql = "SELECT Organization_Name FROM organizations;";
        Connection connection = mysqlConnection.getConnection();
        PreparedStatement pst = connection.prepareStatement(Sql);
        ResultSet rs = pst.executeQuery();
        while(rs.next()){
            CompanySelect.addElement(rs.getString(1));
            
        }
    }

    private void PopulateProductList() throws SQLException {
        DefaultTableModel ProductsTable = (DefaultTableModel) tblCustomerProductView.getModel();
        String SelectedStore = (String) cbxSelectStore.getSelectedItem();
        String SelectCategory = (String) cbxCategory.getSelectedItem();
        if(SelectedStore == null){
            JOptionPane.showMessageDialog(this, "Please Select Store");
        }
        else{
            ResultSet rs1 = Products.GetAllDataFromProductsTable(SelectedStore,SelectCategory);
            
            ResultSetMetaData metaData = (ResultSetMetaData) rs1.getMetaData();
            int columnCount = metaData.getColumnCount();
            ProductsTable.setRowCount(0);
        
            Object[] row = new Object[columnCount];
            while (rs1.next()){
                //Get object from column with specific index of result set to array of objects
                for (int i = 0; i < columnCount; i++){
                    row[i] = rs1.getObject(i+1);
                }
                //Now add row to table model with that array of objects as an argument
                ProductsTable.addRow(row);
            }
            
            
            }
    }
    
    
    
    
    
}

